name: CI - frontendproxy

on:
  push:
    paths:
      - 'src/frontend-proxy/**'
      - '.github/workflows/frontendproxy-ci.yml'
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: yourdockerhubusername/frontendproxy
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG -f Dockerfile .

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG

  update-manifest:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update image in Kubernetes manifest
        run: |
          sed -i "s|image: .*|image: $IMAGE_NAME:$IMAGE_TAG|" opentelemetry-demo/templates/component.yaml

      - name: Commit updated manifest
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add opentelemetry-demo/templates/component.yaml
          git commit -m "Update frontendproxy image to $IMAGE_TAG"
          git push origin main
